services:
  - type: web
    name: niffty
    runtime: node
    repo: https://github.com/8619747559rahulkumawat/niffty
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@digitalsms.biz
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: https://niffty.onrender.com
      - key: CLEANUP_SCHEDULE
        value: 0 3 * * *
      - key: OPENAI_API_KEY
        sync: false
