services:
  - type: web
    name: niffty-backend
    runtime: node
    repo: https://github.com/8619747559rahulkumawat/niffty
    plan: free
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@digitalsms.biz
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: https://niffty-backend.onrender.com
      - key: CLEANUP_SCHEDULE
        value: 0 3 * * *